# The Azure pipeline builds the x86 and x64 release builds.
# No testing is performed in the pipeline, as that would need Excel installed on the build agent.

trigger:
- master

variables:
  solution: '**/excelbind.sln'
  buildConfiguration: 'Release'

jobs:
- job: 'Build'
  strategy:
    matrix:
      2015_Release_Win32:
        pythonVersion: '3.6'
        buildPlatformPython: 'x86'
        buildPlatform: 'Win32'
        buildConfiguration: 'Release'
        vsNumber: 2015
        vsName: 'Visual Studio 14 2015'
        imageName: 'vs2015-win2012r2'

      2015_Release_x64:
        pythonVersion: '3.6'
        buildPlatformPython: 'x64'
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
        vsNumber: 2015
        vsName: 'Visual Studio 14 2015'
        imageName: 'vs2015-win2012r2'

      2017_Release_Win32:
        pythonVersion: '3.7'
        buildPlatformPython: 'x86'
        buildPlatform: 'Win32'
        buildConfiguration: 'Release'
        vsNumber: 2017
        vsName: 'Visual Studio 15 2017'
        imageName: 'vs2017-win2016'

      2017_Release_x64:
        pythonVersion: '3.7'
        buildPlatformPython: 'x64'
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
        vsNumber: 2017
        vsName: 'Visual Studio 15 2017'
        imageName: 'vs2017-win2016'

      2019_Release_Win32:
        pythonVersion: '3.7'
        buildPlatformPython: 'x86'
        buildPlatform: 'Win32'
        buildConfiguration: 'Release'
        vsNumber: 2019
        vsName: 'Visual Studio 16 2019'
        imageName: 'windows-latest'

      2019_Release_x64:
        pythonVersion: '3.7'
        buildPlatformPython: 'x64'
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
        vsNumber: 2019
        vsName: 'Visual Studio 16 2019'
        imageName: 'windows-latest'

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: true
    persistCredentials: true
    
  - task: UsePythonVersion@0
    condition: ne(variables['vsNumber'], 2015)
    inputs:
      versionSpec: $(pythonVersion)
      addToPath: true
      architecture: $(buildPlatformPython)

  - script: set
    displayName: View env vars

  - task: NuGetToolInstaller@1

  - task: CmdLine@2
    inputs:
      script: |
        cmake -S src -B build/$(vsNumber)$(buildPlatform) -G "$(vsName)" -A $(buildPlatform)

  - task: VSBuild@1
    inputs:
      solution: 'build/$(vsNumber)$(buildPlatform)/excelbind.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: CmdLine@2
    condition: eq(variables['vsNumber'], 2019)
    inputs:
      script: |
        git config user.email "53918463+RuneLjungmann@users.noreply.github.com"
        git config user.name "RuneLjungmann"
        git checkout master
        git commit -a -m "Azure Pipeline: Updated binaries" -m "[skip ci]"
        git push origin