# The Azure pipeline builds the x86 and x64 release builds.
# No testing is performed in the pipeline, as that would need Excel installed on the build agent.

trigger:
- master

variables:
  solution: '**/excelbind.sln'
  buildConfiguration: 'Release'


jobs:
- job: 'Build' 
  strategy:
    matrix:
      x86:
        buildPlatform: 'x86'
      x64:
        buildPlatform: 'x64'

  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: $(buildPlatform)

  - script: set
    displayName: View env vars

  - task: NuGetToolInstaller@1

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: CopyFiles@2
    inputs:
      Contents: '**/excelbind.xll'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(buildPlatform)'
      publishLocation: 'Container'